"""Set accurate shipment fileds to not nullable

Revision ID: 9ea8d730a9b2
Revises: f0bf7fd1134b
Create Date: 2025-10-27 11:20:13.492278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ea8d730a9b2"
down_revision: Union[str, Sequence[str], None] = "f0bf7fd1134b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shipments", "min_temp", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("shipments", "max_temp", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("shipments", "min_humidity", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("shipments", "max_humidity", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("shipments", "delivery_address", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("shipments", "pickup_address", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shipments", "pickup_address", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("shipments", "delivery_address", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("shipments", "max_humidity", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("shipments", "min_humidity", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("shipments", "max_temp", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("shipments", "min_temp", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
