"""Update shipment model with new fields

Revision ID: f0bf7fd1134b
Revises: 287246b0adf9
Create Date: 2025-10-27 10:08:56.682227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0bf7fd1134b"
down_revision: Union[str, Sequence[str], None] = "287246b0adf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    shipment_status_enum = sa.Enum("created", "assigned", "in_transit", "delivered", "cancelled", name="shipmentstatus")
    shipment_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipments",
        sa.Column(
            "status",
            sa.Enum("created", "assigned", "in_transit", "delivered", "cancelled", name="shipmentstatus"),
            nullable=False,
            server_default="created",
        ),
    )
    op.add_column("shipments", sa.Column("min_temp", sa.Integer(), nullable=True))
    op.add_column("shipments", sa.Column("max_temp", sa.Integer(), nullable=True))
    op.add_column("shipments", sa.Column("min_humidity", sa.Integer(), nullable=True))
    op.add_column("shipments", sa.Column("max_humidity", sa.Integer(), nullable=True))
    op.add_column("shipments", sa.Column("delivery_address", sa.String(length=255), nullable=True))
    op.add_column("shipments", sa.Column("pickup_address", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipments", "pickup_address")
    op.drop_column("shipments", "delivery_address")
    op.drop_column("shipments", "max_humidity")
    op.drop_column("shipments", "min_humidity")
    op.drop_column("shipments", "max_temp")
    op.drop_column("shipments", "min_temp")
    op.drop_column("shipments", "status")

    shipment_status_enum = sa.Enum(name="shipmentstatus")
    shipment_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
