name: CI v1 Tests, Build docker image and Push to Docker Hub. 

on: 
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs: 
  Tests:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Set up Python environment
          uses: actions/setup-python@v6
          with: 
            python-version: '3.13'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run tests
          run: pytest -v 
        
        - name: All tests passed
          if: success()
          run: echo "All tests passed!"

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
            
        - name: Build Docker Image
          run: |
            BRANCH=${GITHUB_REF##*/}
            if [ "$BRANCH" == "main" ]; then
              IMAGE_TAG="main-latest"
            elif [ "$BRANCH" == "develop" ]; then
                IMAGE_TAG="develop-latest"
            else
              IMAGE_TAG="latest"
            fi
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

            docker build -t annaschwartzchas/chas_advance_backend:$IMAGE_TAG .

        - name: Test Docker image with health check
          run: |
            docker run -d --name backend_test -p 8000:8000 -e DATABASE_URL=${{ secrets.DATABASE_URL }} annaschwartzchas/chas_advance_backend:$IMAGE_TAG
            for i in {1..10}; do
              if curl -s http://localhost:8000/health | grep -q "ok"; then
                echo "Health check passed!"
                break
              else
                echo "Waiting for the container to start..."
                sleep 5
              fi
            done
            docker stop backend_test
            docker rm backend_test
        
        - name: Push Docker Image to Docker Hub
          run: |
            docker push annaschwartzchas/chas_advance_backend:$IMAGE_TAG