name: CI v1 Tests, Build docker image and Push to Docker Hub. 

on: 
  push:
    branches:
      #- main
      #- develop
      - 14-7110-create-dockerfile-for-backend-that-builds-our-project-ensure-it-can-be-composed-with-docker-compose
  workflow_dispatch:

jobs: 
  Tests:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Set up Python environment
          uses: actions/setup-python@v6
          with: 
            python-version: '3.13'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run tests
          run: pytest -v 
        
        - name: All tests passed
          if: success()
          run: echo "All tests passed!"

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
            
        - name: Build Docker Image
          run: |
            BRANCH=${GITHUB_REF##*/}
            if [ "$BRANCH" == "main" ]; then
              IMAGE_TAG="main-latest"
            elif [ "$BRANCH" == "develop" ]; then
                IMAGE_TAG="develop-latest"
            else
              IMAGE_TAG="latest"
            fi
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

            docker build -t annaschwartzchas/chas_advance_backend:$IMAGE_TAG .

        - name: Test Docker image with temporary Postgres database
          run: |
            # Start a temporary Postgres container (Can be changed to a real testdatabase later on)  
            docker run -d --name ci_postgres \
            -e POSTGRES_USER=test \
            -e POSTGRES_PASSWORD=test \
            -e POSTGRES_DB=testdb \
            -p 5432:5432 \
            postgres:15

            # Wait for Postgre to be ready
            sleep 10

            export DATABASE_URL="postgresql+psycopg://test:test@localhost:5432/testdb"
            
            sudo apt-get update && sudo apt-get install -y jq

            docker run -d --name backend_test -p 8000:8000 -e DATABASE_URL="$DATABASE_URL" annaschwartzchas/chas_advance_backend:${{ env.IMAGE_TAG }}
           
            HEALTH_CHECK_PASSED=false
            for i in {1..10}; do
              if curl -s http://localhost:8000/health | jq -e '.status=="ok"' > /dev/null; then
                echo "Health check passed!"
                HEALTH_CHECK_PASSED=true
                break
              else
                echo "Waiting for the container to start..."
                sleep 5
              fi
            done

            docker stop backend_test ci_postgres
            docker rm backend_test ci_postgres

            if [ "$HEALTH_CHECK_PASSED" = false ]; then
              echo "Health check failed after 10 attempts"
              exit 1
            fi    
        
        - name: Push Docker Image to Docker Hub
          run: |
            docker push annaschwartzchas/chas_advance_backend:${{ env.IMAGE_TAG }}