name: CI v2 Tests, Build docker image and Push to Docker Hub.

on:
  push:
    branches:
      #- main
      #- develop
      - 77-7126-refactor-workflow-that-publishes-docker-image
  workflow_dispatch:

jobs:
  Tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

      - name: All tests passed
        if: success()
        run: echo "All tests passed!"

  Docker_Build_and_Test_AMD64_Image:
    name: Builds and Tests AMD64 Docker Image
    runs-on: ubuntu-latest
    needs: Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build amd64 Docker Image for testing
        run: docker buildx build --platform linux/amd64 -t backend_test_amd64 --load .

      - name: Make scripts executable
        run: chmod +x .github/scripts/tests.sh

      - name: Test Docker image
        run: .github/scripts/tests.sh backend_test_amd64
        env:
          TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
          SECRET_KEY_TEST: ${{ secrets.SECRET_KEY_TEST }}

  Docker_Build_and_Test_ARM64_Image:
    name: Builds and Tests ARM64 Docker Image
    runs-on: ubuntu-24.04-arm
    needs: Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build arm64 Docker Image for testing
        run: docker buildx build --platform linux/arm64 -t backend_test_arm64 --load .

      - name: Make scripts executable
        run: chmod +x .github/scripts/tests.sh

      - name: Test Docker image
        run: .github/scripts/tests.sh backend_test_arm64
        env:
          TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
          SECRET_KEY_TEST: ${{ secrets.SECRET_KEY_TEST }}

  Docker_Build_and_Push_Docker_Image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs:
      [Docker_Build_and_Test_AMD64_Image, Docker_Build_and_Test_ARM64_Image]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Determine next Docker tag
        run: |
          chmod +x .github/scripts/version.sh
          .github/scripts/version.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Multi-Arch Docker Image
        run: |
          if [ "${GITHUB_REF##*/}" == "develop" ]; then
            docker buildx build --platform linux/amd64,linux/arm64 \
              -t annaschwartzchas/chas_advance_backend:${IMAGE_TAG} \
              -t annaschwartzchas/chas_advance_backend:latest \
              --build-arg VERSION=${IMAGE_TAG} \
              --push .
          else
            docker buildx build --platform linux/amd64,linux/arm64 \
              -t annaschwartzchas/chas_advance_backend:${IMAGE_TAG} \
              --build-arg VERSION=${IMAGE_TAG} \
              --push .
          fi
