name: CI v1 Tests, Build docker image and Push to Docker Hub. 

on: 
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs: 
  Tests:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Set up Python environment
          uses: actions/setup-python@v6
          with: 
            python-version: '3.13'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run tests
          run: pytest -v 
        
        - name: All tests passed
          if: success()
          run: echo "All tests passed!"