name: Version Bump

on:
    push:
        branches:
            - develop
            - main
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    bump-version:
        runs-on: ubuntu-latest
        # Workflow does not run on forks (Security measure)
        if: ${{ github.event.repository.fork == false }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5.0.0
              with:
                  fetch-depth: 0 #Fetch all history to be able to compare version.

            - name: Check if VERSION was updated recently
              id: check
              run: |
                  if git diff HEAD~1 --name-only | grep -q "^VERSION$"; then
                    echo "Version already bumped in the last commit. Skipping version bump."
                    echo "bump_needed=false" >> $GITHUB_ENV
                  else
                    echo "bump_needed=true" >> $GITHUB_ENV
                  fi

            - name: Exit if no bump needed
              if: env.bump_needed == 'false'
              run: |
                  echo "No version bump needed. Exiting workflow."
                  exit 0

            - name: Generate GitHub App token
              if: env.bump_needed == 'true'
              id: generate_token
              uses: actions/create-github-app-token@v1.1.0
              with:
                  app_id: ${{ secrets.APP_ID }}
                  private_key: ${{ secrets.PRIVATE_KEY }}

            - name: Make script executable
              if: env.bump_needed == 'true'
              run: chmod +x .github/scripts/bump_version.sh

            - name: Bump version
              if: env.bump_needed == 'true'
              run: .github/scripts/bump_version.sh

            - name: Log version
              if: env.bump_needed == 'true'
              run: echo "New version is ${{ env.VERSION }}"

            - name: Commit and create PR
              if: env.bump_needed == 'true'
              env:
                  GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  BRANCH_NAME="version-bump-${{ github.ref_name }}-${{ github.run_number }}"
                  git checkout -b $BRANCH_NAME
                  git add VERSION
                  git commit -m "Bump version to ${{ env.VERSION }}"
                  git push origin "$BRANCH_NAME"

                  gh pr create \
                  --title "Bump version to ${{ env.VERSION }}" \
                  --body "Automatic version bump to ${{ env.VERSION }} from ${{ github.ref_name}}" \
                  --base ${{ github.ref_name }} \
                  --head "$BRANCH_NAME"
